### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by Nalisarc** [durableOne/orgmunge#1]
Hello friend! 
This library looks really cool, but could use some tests to aid with development and collaboration.
I've written a few using pytest, and then pipenv to manage dependencies. 

This issue is just so I can point my PR once it's ready.

**Comment by durableOne** [comment]
Sounds great! Please let me know what testing framework you plan on using so that if I get to writing tests before you submit a PR, I'll make sure to write them in the same framework.

**Comment by durableOne** [comment]
Closing since I merged [your pull request](https://github.com/durableOne/orgmunge/pull/4)
