### ISSUE TITLE
Error: TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by crdoconnor** [durableOne/orgmunge#15]
This one came from [the first bug report on my app](https://github.com/crdoconnor/orji/issues/1) based upon orgmunge.

I'm not sure why the reporter got this error, but I managed to reproduce it by saving an empty files in orgzly which only has a preface:

```
This is my preface\n\n
```

It appears that the bug is only reproduceable on files which have a preface but no notes. If there is no preface and no notes (i.e. empty file) or notes but no preface then it works just fine.

Once again, thanks for all the awesome work.

**Comment by durableOne** [comment]
Thanks for reporting this upstream. Fixed in https://github.com/durableOne/orgmunge/commit/c42897e720f74417673e5f04b64b2763252f3109

**Comment by crdoconnor** [comment]
Amazing, thanks!

**Comment by durableOne** [comment]
Released v0.2.1 to PyPi with the fix. Apologies for the delay.
