### ISSUE TITLE
install from pip

### ISSUE THREAD

**Issue by Nalisarc** [durableOne/orgmunge#2]
Being able to install this via pip either from pypy itself or as a zip would make using this project easier for new users and collaborators.
There are a few ways to approach this, personally I was going to use a combo of pipenv pipenv-setup and setuptools the distributing it via pypy. 

If your not opposed to that I'd be more than happy to share my setup.py, setup.cfg and pipfile once they are ready.
Then you would be able to upload the repo to pypy using setuptools.

**Comment by durableOne** [comment]
This is one of the items on my list. The only reason I haven't done it yet is that I need to look into the requirements (I have never pushed anything to PyPi before).

**Comment by Nalisarc** [comment]
I have this sample module that covers a basic setup.py 
https://github.com/Nalisarc/samplemod
From what I understand we can then upload it to pypi using twine.

You'll need to register an account here: https://pypi.org/account/register/

**Comment by Nalisarc** [comment]
I'm continuing to work on this, but I wanted to help out more. 
I've started work on the github actions, these should help the project be more robust as you, I, and any other collaborators work on this. 

I'm also trying to be better about my branches.

**Comment by Nalisarc** [comment]
Okay so a couple of directory rearrangements were needed. But I haven't needed to make any changes to the code itself!
If we structure the directory like so:
orgmunge/
 - pyproject.toml
 - README.org
 - tests/
 - src/
   - orgmunge/
   
  
 
This allows build and pip-tools to build a  copy of the library and install it like a module. 
I can then use twine to upload to test-pip. Once this is done I'll send you another message with instructions to upload it to real pip.
I'm super excited about making this library more usable.

**Comment by crdoconnor** [comment]
Was this package not put on pypi by you? https://pypi.org/project/orgmunge/

**Comment by Nalisarc** [comment]
Yeah that looks like us! 
It also installs version 0.1.1. 

Thanks for bring this to my attention.

**Comment by durableOne** [comment]
@Nalisarc, I know I've been delaying looking into this because I have no past experience with publishing to PyPi, but I don't think it's fair that you published this package and listed yourself as author. Please change the author field to my name.

**Comment by crdoconnor** [comment]
@durableOne you're listed as maintainer on pypi too are you sure you're not able to do this?

**Comment by Nalisarc** [comment]
I took a look and made sure you're listed as owner. Then removed myself as an owner. 
You should now be the only owner there. 

It was never my intention to claim ownership over the project. 
My apologies for the confusion.

**Comment by durableOne** [comment]
> I took a look and made sure you're listed as owner. Then removed myself as an owner. You should now be the only owner there.
> 
> It was never my intention to claim ownership over the project. My apologies for the confusion.

I apologize if my initial message sounded too harsh. I now see the misunderstanding that happened. I never meant for you to remove yourself as a co-maintainer. I just meant that I should be listed as **author**. This should be fixed on a re-upload since I fixed the pyproject.toml file.
Please add yourself back as a maintainer on the package if you are still willing to work on it, I really value your contribution.

**Comment by Nalisarc** [comment]
No worries! I am still willing to work on this. 
From what I gather, the scripts I wrote for the .github/workflow used me as the author. Which was never my intention.
You might need to re-add me as a contributor on pypi? the username I used was deltazeeter. 

I've always thought that this is your project. I'm just happy to contribute what skill I have.
