### ISSUE TITLE
need pyproject.toml or equivalent

### ISSUE THREAD

**Issue by Nalisarc** [durableOne/orgmunge#7]
Hey wanted to work on this a bit more, and I think I have some stuff that would help more.
First things first is a pyproject.toml, setup.py or setup.cfg.
This tells pythons the details about the package, like what version it is, and who wrote it.
I have most of one drafted up based on [this tutorial](https://realpython.com/pypi-publish-python-package/).

Once it's ready I'm gonna do a pull request, and I'll need you to add your details to it.

Thank you~

**Comment by Nalisarc** [comment]
I've stolen https://github.com/ispringle 's solution of using poetry.
The version I've created will close this issue.  

This has a number of benefits. 
mostly when building and pushing things to pypi.
When combined with my other changes https://github.com/durableOne/orgmunge/issues/2 will be solved as well~

Have a wonderful rest of your week.

**Comment by durableOne** [comment]
Fixed by merging 
https://github.com/durableOne/orgmunge/pull/8
